version: 2
updates:

  - package-ecosystem: "github-actions"
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: 'action-deps: '

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: 'nuget-deps: '
